services:
  # H2 Database Service
  db:
    build:
      context: .
      dockerfile: DockerfileDB
    container_name: cogsi_h2_database
    volumes:
      - ./db-data:/opt/h2-data
    networks:
      cogsi_network:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD-SHELL", "nc -z 172.20.0.10 9092 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Spring Boot Application Service
  app:
    build:
      context: .
      dockerfile: DockerfileApp
      args:
        - REPO_URL=https://1201264isep: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@github.com/pedroteixeira80/cogsi2526-1201264-1210901-1210902.git
    container_name: cogsi_spring_app
    ports:
      - "8080:8080" # Spring Boot application (http://localhost:8080)
    environment:

      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:9092/./h2-data/jpadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
    networks:
      cogsi_network:
        ipv4_address: 172.20.0.20
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

# Define the network for communication between services
networks:
  cogsi_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
